export { setupAntd } from './antd'
export { setupAssets } from './assets'
export { setupPlugins } from './customPlugins'
export { setupDirectives } from './directives'
export { setupComponents } from './customComponents'
export { setupGlobalMethods } from './globalMethods'